version: '2'

services:

  master:
    image: eric/jmeter_master:3.0
    container_name: master
    tty: true
    hostname: master
    networks:
      - vins
  slave:
    image: eric/jmeter_server:2.0
    tty: true
    networks:
      - vins

networks:
  vins:
    driver: bridge
